modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
logoFile="hunterx_logo.png" #optional
[[mods]] #mandatory
modId="hntrx" #mandatory
version="0.2.2" #mandatory
displayName="HunterX" #mandatory
credits="Izako, Snooker, Hypnoman, FGPisces, Delend" #optional
authors="Izako, Snooker, Hypnoman" #optional
description='''
HunterX is a minecraft mod made to put the world of hunter x hunter into minecraft.
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.HunterX]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
